### ISSUE TITLE
Websocket unable to connect

### ISSUE THREAD

**Issue by torchsmith** [GRVYDEV/Lightspeed-webrtc#14]
Error from browser in console `xxx` is public IP address of server:
`App.js:21 WebSocket connection to 'ws://xxx:8080/websocket' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED`

`Socket encountered error:  undefined Closing socket`

Command run on server `xxx` is private IP address of server:
`./lightspeed-webrtc --addr=xxx`

**Comment by GRVYDEV** [comment]
Check your firewall settings

**Comment by torchsmith** [comment]
So I completely disabled all firewall rules and I'm still running into this problem. Any other suggestions?

**Comment by Scrumplex** [comment]
maybe try `--addr=0.0.0.0` which should listen on all (IPv4) addresses. That makes it available from everywhere

**Comment by GRVYDEV** [comment]
Where are you trying to connect from? Localhost? If so then the xxx for the websocket should be `ws://localhost:8080/websocket` and --addr should be localhost (which is its default value so you can just not pass this arg) as well

**Comment by torchsmith** [comment]
Server running the WebRTC and Ingest servers. I've tried connecting from both my local PC, and serving the React app from the server itself and have had no luck. I'll try using --addr=0.0.0.0

**Comment by torchsmith** [comment]
![image](https://user-images.githubusercontent.com/14154207/103700137-64c26d00-4f7a-11eb-8022-03e1cc4a84ea.png)

New console log returned when setting --addr to 0.0.0.0

**Comment by GRVYDEV** [comment]
> ![image](https://user-images.githubusercontent.com/14154207/103700137-64c26d00-4f7a-11eb-8022-03e1cc4a84ea.png)
> 
> New console log returned when setting --addr to 0.0.0.0

Boom its working!

**Comment by GRVYDEV** [comment]
Since autoplay is broken you will need to manually press the play button to see the stream

**Comment by torchsmith** [comment]
![image](https://user-images.githubusercontent.com/14154207/103700218-8ae80d00-4f7a-11eb-9a03-b02f2f8e1430.png)

Getting this error on WebRTC now.

**Comment by GRVYDEV** [comment]
pull from main on lightspeed-webrtc :)

**Comment by torchsmith** [comment]
Ok!

**Comment by GRVYDEV** [comment]
> Ok!

Apparently OBS on windows sends some packets that arent the proper RTP format so I had to just ignore those

**Comment by torchsmith** [comment]
Finally working. Niiiice.
