### ISSUE TITLE
Stutter Frames

### ISSUE THREAD

**Issue by torchsmith** [GRVYDEV/Lightspeed-webrtc#15]
I'm noticing that I get a frame stutter every couple seconds. Any ideas?

**Comment by GRVYDEV** [comment]
What bitrate?

**Comment by torchsmith** [comment]
Was just using the default of 2500 kbps.

**Comment by torchsmith** [comment]
It looks like the Ingest log is saying 1280x720 but I'm streaming in 4K data. Anything seem wrong there? hmm..

**Comment by GRVYDEV** [comment]
> It looks like the Ingest log is saying 1280x720 but I'm streaming in 4K data. Anything seem wrong there? hmm..

I think that is a bug with the FTL SDK or something. I am streaming at 1080 right now and it says 720 but I can tell its 1080

**Comment by torchsmith** [comment]
Ok, the quality visually checks out for sure. Nonetheless the frames still drop here and there. I don't think it's my OBS, it's not showing any dropped frames, although I'll mess around with my settings in there a bit more.

**Comment by torchsmith** [comment]
Ok, looks like it may have been that I was using the software encoder and not hardware encoder. Whoops! I'll reopen this if I see it persist though.
