### ISSUE TITLE
Socket periodically closes

### ISSUE THREAD

**Issue by r4rdsn** [GRVYDEV/Lightspeed-webrtc#22]
Each ~50-60 seconds socket closes and immediately reconnects, causing stream to lag for several seconds before reloading the player.
Console output:
```
App.js:36 Socket is closed. Reconnect will be attempted in 0.5 second. 
App.js:26 Connected to websocket
```
lightspeed-webrtc output:
```
websocket: close 1006 (abnormal closure): unexpected EOF
Connections: 1
```

**Comment by GRVYDEV** [comment]
Close 1006 is a configuration error. What browser are you connecting from?

**Comment by r4rdsn** [comment]
Same issue on Firefox 78.6.0esr and Chromium 83.0.4103.97

**Comment by r4rdsn** [comment]
Turns out the problem was my nginx reverse proxy configuration in https://github.com/GRVYDEV/Lightspeed-webrtc/issues/13#issue-778985497. By default nginx request timeout is set to 60 seconds, I've added `proxy_read_timeout 86400s;` for 24 hours and the issue is gone. I'll update my configuration in that issue accordingnly, in case anyone will want to use it. Thank you!
